### ISSUE TITLE
temporary error when uploading with mdsync

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#18]
While uploading content to the server, I am always seeing an error on the first attempt, even if only uploading a couple of files.

local console:

> mdsync
> 2024-09-30 10:23:12.578 | INFO     | markopolis.upload:mdsync:56 - url: index.md
> 2024-09-30 10:23:12.578 | INFO     | markopolis.upload:mdsync:61 - Uploading index.md
> 2024-09-30 10:23:14.923 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded index.md
> 2024-09-30 10:23:14.924 | INFO     | markopolis.upload:mdsync:56 - url: Trip itinerary.md
> 2024-09-30 10:23:14.924 | INFO     | markopolis.upload:mdsync:61 - Uploading Trip itinerary.md
> 2024-09-30 10:23:15.137 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload Trip itinerary.md. Status code: 500
> 2024-09-30 10:23:15.137 | INFO     | markopolis.upload:mdsync:56 - url: Plan.md
> 2024-09-30 10:23:15.137 | INFO     | markopolis.upload:mdsync:61 - Uploading Plan.md
> 2024-09-30 10:23:15.292 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload Plan.md. Status code: 500
> 2024-09-30 10:23:15.293 | INFO     | markopolis.upload:mdsync:56 - url: Stays.md
> 2024-09-30 10:23:15.293 | INFO     | markopolis.upload:mdsync:61 - Uploading Stays.md
> 2024-09-30 10:23:15.452 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload Stays.md. Status code: 500
> 
> Personal/Publish/public took 3s 
> mdsync
> 2024-09-30 10:23:23.305 | INFO     | markopolis.upload:mdsync:56 - url: index.md
> 2024-09-30 10:23:23.305 | INFO     | markopolis.upload:mdsync:61 - Uploading index.md
> 2024-09-30 10:23:23.537 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded index.md
> 2024-09-30 10:23:23.537 | INFO     | markopolis.upload:mdsync:56 - url: Trip itinerary.md
> 2024-09-30 10:23:23.537 | INFO     | markopolis.upload:mdsync:61 - Uploading Trip itinerary.md
> 2024-09-30 10:23:23.742 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded Trip itinerary.md
> 2024-09-30 10:23:23.743 | INFO     | markopolis.upload:mdsync:56 - url: Plan.md
> 2024-09-30 10:23:23.743 | INFO     | markopolis.upload:mdsync:61 - Uploading Plan.md
> 2024-09-30 10:23:24.119 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded Plan.md
> 2024-09-30 10:23:24.120 | INFO     | markopolis.upload:mdsync:56 - url: Stays.md
> 2024-09-30 10:23:24.120 | INFO     | markopolis.upload:mdsync:61 - Uploading Stays.md
> 2024-09-30 10:23:24.330 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded Stays.md

From the container I get the following with the same timestamps as the initial mdsync

> login valid
> Attachments collection does not exist. Creating...
> Attachments collection created successfully
> Mdbase collection does not exist. Creating...
> Mdbase collection created successfully with index on url field
> Tags collection does not exist. Creating...
> tags collection created successfully
> front { publish: 'true', title: 'Home', date: null, mdpath: 'index.md' }
> WIKI =====> [ '/Trip itinerary.md', '/Plan.md', '/Stays.md' ]
> Updated bi-directional links
> Updated note z6hhe7zdnx7ayad with tags: 
> Updated  tags
> Attachments collection already exists
> Mdbase collection already exists
> Adding links field to mdbase collection...
> Links field added successfully
> Adding links field to mdbase collection...
> Error checking mdbase collection: ClientResponseError 400: Failed to update the collection.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async ensureMdbaseCollection (file:///app/build/server/chunks/_server.ts-BA5eux20.js:1248:7)
>     at async file:///app/build/server/chunks/_server.ts-BA5eux20.js:1517:7
>     at async render_endpoint (file:///app/build/server/index.js:1185:20)
>     at async resolve2 (file:///app/build/server/index.js:3672:22)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async Array.ssr (file:///app/build/handler.js:1262:3) {
>   url: 'http://127.0.0.1:8080/api/collections/mdbase',
>   status: 400,
>       message: 'Failed to update the collection.',
>       data: {}
>     }
>   }
> }
> Error in upload API: ClientResponseError 400: Failed to update the collection.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async ensureMdbaseCollection (file:///app/build/server/chunks/_server.ts-BA5eux20.js:1271:7)
>     at async file:///app/build/server/chunks/_server.ts-BA5eux20.js:1517:7
>     at async render_endpoint (file:///app/build/server/index.js:1185:20)
>     at async resolve2 (file:///app/build/server/index.js:3672:22)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async Array.ssr (file:///app/build/handler.js:1262:3) {
>   url: 'http://127.0.0.1:8080/api/collections/mdbase',
>   status: 400,
>   response: { code: 400, message: 'Failed to update the collection.', data: {} },
>   isAbort: false,
>   originalError: {
>     url: 'http://127.0.0.1:8080/api/collections/mdbase',
>     status: 400,
>     data: {
>       code: 400,
>       message: 'Failed to update the collection.',
>       data: {}
>     }
>   }
> }

It does work without any issues when I do mdsync again - but obviously it shouldn't be failing the first time around.

**Comment by rishikanthc** [comment]
Yeah I have been noticing this in my usage as well. From my experience it tends to fail on a couple of notes and when I run it again it succeeds. I think it has something to do with notes with some special characteristics but I haven't gotten time to probe in to it in detail. Will check what's going on. If you ever notice anything specific or particular notes behaving weirdly do let me know as it might help in debugging. Otherwise I'll try to narrow down manually.

**Comment by cromelex** [comment]
Will do. So far I only saw this on the first instance of uploading to a server (running 2 different servers, and happened on both).

Not seeing any patterns so far on the failing notes.
The second `mdsync` worked just 10 seconds after the first one.
